name: CI/CD Pipeline 

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Test HTML
      run: npx htmlhint .

    - name: Send logs to CloudWatch
      uses: aws-actions/cloudwatch-logs-action@v2
      with:
        log_group_name: /github-actions
        log_stream_name: html-lint
        log_text: Completed HTML linting

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - uses: actions/download-artifact@v2
      with:
        name: html-files

    - name: Deploy to S3
      run: aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --delete

    - name: Send deployment time metric
      uses: awact/cloudwatch-metric-action@v1
      with:
        metric-name: DeploymentTime
        metric-value: ${{ steps.get_deploy_time.outputs.duration }}
        metric-unit: Seconds
