name: CI/CD Pipeline 

on:
  push:
    branches:
      - main

env:
  DATADOG_SITE: ${{ secrets.DATADOG_SITE }}
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Datadog agent
      uses: DataDog/datadog-agent-github-action@master
      with:
        site: ${{ env.DATADOG_SITE }}
        apiKey: ${{ env.DATADOG_API_KEY }}
        hostname: github-runner
        tags: env:github-actions,workflow:${{ github.workflow }}

    - name: Test HTML
      run: |
        npx htmlhint .
        echo "Completed HTML linting"

    - name: Send logs to Datadog  
      uses: DataDog/datadog-action-step@main
      with:
        logs: 'Completed HTML linting'

    - name: Copy files to artifact
      run: |  
        mkdir html-files
        rsync -av --exclude html-files/ . html-files/
        rm -r html-files/.git

    - name: Upload artifact 
      uses: actions/upload-artifact@v2
      with:
        name: html-files
        path: html-files

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: html-files
        path: ./  

    - name: Deploy to S3
      run: | 
        aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --delete

    - name: Log deployment time
      run: |
        start=$(date +%s)

        # deployment steps

        end=$(date +%s)
        duration=$((end-start)) 
        echo "Deploy time: $duration seconds"

    - name: Send deployment event to Datadog
      uses: DataDog/datadog-action-step@main
      with:
        logs: Deployment completed in $duration seconds

    # Other monitoring steps
