name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test HTML
      run: npx htmlhint .

    - name: Copy files to artifact 
      run: |
       mkdir html-files
       rsync -av --exclude html-files/ . html-files/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: html-files
        path: html-files

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: html-files
        path: ./

    - name: Deploy to S3
      run:  |
        aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} --delete
